name: Deploy to Hostinger - sms.clappakistan.com

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to Hostinger
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        echo "Starting deployment to sms.clappakistan.com"
        lftp -e "mirror -R ./ /public_html/sms; quit" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
